name: Manon Lorcery
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 2 * * 1-7"
  workflow_dispatch:
    
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v

    
